version: '3.5'

services:

  peredelano_entry_bot:
    container_name: "peredelano_entry_bot"
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME:-PEREDELANO_ENTRY_BOT}"
    env_file:
      - .env
    image: "ghcr.io/openworld-community/peredelano_entry_bot:${TAG:-latest}"
    build:
      context: ./
      dockerfile: Dockerfile
      target: release
    restart: "${DOCKER_RESTART_POLICY:-always}"
